### ISSUE TITLE
Presence of Obfuscated and Minified JavaScript Files in Test Suite Poses Security Risk And Loss of User Data

### ISSUE THREAD

**Issue by vetalapo** [AlreadyBored/basic-js#164]
Hello there,

I hope this message finds you well. I am writing to bring your attention to a critical issue identified in the test suite of the [basic-js](https://github.com/AlreadyBored/basic-js) GitHub repository. The concern revolves around the presence of obfuscated and minified JavaScript files within the test suite, for which no corresponding source code is available.

**Issue Description**:
The current state of the test suite includes JavaScript files that have been obfuscated and minified, making it impossible to review and rebuild the code to confirm its content. This lack of transparency raises serious security concerns, as it introduces the risk of potential malicious code that could compromise the integrity of the repository and, consequently, the security of user data.

**Potential Implications**:
Security Risk: The obfuscated code may contain malicious elements that could compromise the security of the entire repository and, consequently, user data.

**Inability to Verify Code**:
Without access to the source code, it is challenging to verify the legitimacy and security of the obfuscated and minified files.

**Proposed Possible Actions**:
1. Remove files with obfuscation
2. Add description into README
Unfortunately similar proposition was met harshly at RSSchool and was closed right after opening PR: https://github.com/rolling-scopes-school/core-js-conditions-n-loops-tasks/pull/18
3. Introduce running test in a Docker container, this way if a person doesn't trust obfuscation, they can run the tests in a isolated container. Similar to following:
https://github.com/vetalapo/rsschool-projects/blob/main/basic-js/Dockerfile

**Comment by AlreadyBored** [comment]
@vetalapo 
Hi, your concerns are understandable, but in this case, there’s no need to worry. I personally created this obfuscated code and can confirm there are no viruses or malicious software in it. The obfuscated code contains a random sequence generator and the reference solution code, which checks whether they are transformed correctly. Without obfuscation, the reference solution code could be used by students to solve the task, which is why obfuscation is necessary.

If you don't trust this code, you have the following options:

1. Avoid running tests locally on your computer (you can run them on remote servers, such as EC2, for example).
2. Use virtualization technologies (virtual machines, Docker containers, etc.).
3. Choose not to use this code and not to solve this task — this repository is provided "as-is," and I will not implement additional protections against non-existent threats. I maintain this repository and do not include malicious software or viruses in it.
